name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t desafio13 "C:\\Users\\Usuario\\Desktop\\BOOTCAMP\\desafio 12"

      - name: Run Docker Container
        run: |
          docker run -d --name mi_contenedor desafio13

      - name: Testing
        run: |
          # Aquí puedes agregar los comandos necesarios para ejecutar las pruebas de la aplicación

      - name: Publish Image to DockerHub
        run: |
          echo "${{ secrets.DOCKER_USERNAME }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag desafio13 jessiquinterot/desafio13
          docker push jessiquinterot/desafio13

